### ISSUE TITLE
addition of dockstring in the files 

### ISSUE THREAD

**Issue by GionMolf** [GioeleLSPD/The-Framework-Five#36]

**Comment by GionMolf** [comment]
Fixed in b5d2a982fd0e6b9c157bbcb821dbada1579301d9

**Comment by SofiaLoca** [comment]
Fixed in 28fa5c518654919d531e3a3eb3ec890503230910

**Comment by MatiLoca** [comment]
Fixed in 864b0913f1bd0a78708f22a2f3c0c5c66ae111c8

**Comment by U20-LSPD** [comment]
Fixed in:
90f083ccfd73f4765f4c07d5f618e89de8934bc0
07ebdf269839af492c6852c8061642ebafdbca1c
