### ISSUE TITLE
Fixing the README 

### ISSUE THREAD

**Issue by SofiaLoca** [GioeleLSPD/The-Framework-Five#43]

**Comment by MatiLoca** [comment]
I updated part of the ReadME, explained in more details the functionality of our project

**Comment by SofiaLoca** [comment]
fixed in: d05810185d6540a1ddd36e48fddc8acbab85563d

**Comment by MatiLoca** [comment]
fixed in b9caba8db76b4e1264424074b822758db4a0c346
