### ISSUE TITLE
Adding path datased on README.md

### ISSUE THREAD

**Issue by U20-LSPD** [GioeleLSPD/The-Framework-Five#65]
The README.md lacks instructions on the dataset's location and how to access it. For better clarity and ease of use, especially for new contributors, it would be helpful to include detailed information about where the dataset is located and the steps to access or download it.

**Comment by MatiLoca** [comment]
I added the link to kaggle, described the dataset better by adding some details. 
I described our new feature: songs_for_artist 
Fixed in: 3f00198dba5a938018490abd417e811105d9ca39

**Comment by MatiLoca** [comment]
I added the link to kaggle, described the dataset better by adding some details. 
I described our new feature: songs_for_artist 
Fixed in: 3f00198dba5a938018490abd417e811105d9ca39
