### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by U20-LSPD** [GioeleLSPD/The-Framework-Five#68]
The coverage is: main 76% and info 88%, must be 100% for both modules.

**Comment by U20-LSPD** [comment]
test coverage improve ef9d9e4b79bd30572d1d7787dd0d94b70caa8c1f

**Comment by MatiLoca** [comment]
Test coverage improved, 
Fixed in a648706371a16a0a25ab9351769e86af9d2ce934

**Comment by MatiLoca** [comment]
Improved coverage, new def in test_mood.py 
Fixed in 9daf5fd23088dd2ae0c0c45e0c18bff3e222a010

**Comment by U20-LSPD** [comment]
obtained 100% coverage
